### ISSUE TITLE
Non-USD lot currency confuses valuation logic

### ISSUE THREAD

**Issue by yuriizinets** [achannarasappa/ticker#223] opened 2022-04-23 10:07 UTC
**Describe the bug**
When lot currency is not USD (but USD selected as a base display currency), valuation logic still thinks it's USD. 

**To Reproduce**
1. Add any non-USD lot

**Expected behavior**
Take into account lot currency.

**Screenshots**
![image](https://user-images.githubusercontent.com/17050536/164889883-21685721-9ad8-4d62-b9d8-6af4ad22bc92.jpeg)

**Environment (please complete the following information):**
 - OS: Mac
 - Terminal: iTerm
 - Terminal Version: 3.4.15
 - ticker Version: 4.5.1

**Comment by deroshkin** [comment] 2022-08-22 16:38
After messing around with this issue, it seems that it's caused by Yahoo incorrectly formatting the London stock exchange quote currency as GBp instead of GBP, which causes currency conversion error. The same error occurred with London stocks when using CAD as display currency.

I've submitted a pull request #231

**Comment by achannarasappa** [comment] 2022-08-27 12:39
Thanks again for the fix @deroshkin this is addressed in the latest release

**Closed by achannarasappa** 2022-08-27 12:39 UTC
Labels: bug
