### ISSUE TITLE
Holdings formatting wrong when holding >9999

### ISSUE THREAD

**Issue by gabrielpres** [achannarasappa/ticker#145] opened 2021-03-08 16:54 UTC
**Describe the bug**
When "show-holdings: true" in .ticker.yaml, if holdings are >9999 units the formatting and output is wrong (any number > 9999 comes out as "38;5;188m" and also affects the alignment of other fields in the same line

**To Reproduce**
1. Show-holdings: true
3. Put Quantity >9999 for a stock (This might be a common case for "penny stocks")
4. See error when loading. Holdings for that stock is shown as "38;5;188m"

**Expected behavior**
Normal formatting

**Screenshots**
I attach screenshot with holdings 9999 and holdings 10000 of same stock
<img width="938" alt="Screenshot 2021-03-08 at 17 38 33" src="https://user-images.githubusercontent.com/26419521/110353374-4ab71080-8037-11eb-84fe-7ec176c09db6.png">
<img width="938" alt="Screenshot 2021-03-08 at 17 39 02" src="https://user-images.githubusercontent.com/26419521/110353404-530f4b80-8037-11eb-9974-714a3afb2e35.png">

**Environment (please complete the following information):**
 - OS: MAC
 - Terminal: default (ZSH)
 - Terminal Version: 
 - Font: (Optional): Ubuntu Mono

 - ticker Version: 4.0.1

**Comment by achannarasappa** [comment] 2021-03-08 17:37
Thanks for reporting this. I'll put out a fix later today

**Comment by dtcooper** [comment] 2021-03-08 21:47
Dupe of https://github.com/achannarasappa/ticker/issues/143

**Comment by achannarasappa** [comment] 2021-03-08 23:04
Fixed in latest release - added 3 additional digits of space

**Closed by achannarasappa** 2021-03-08 23:04 UTC
Labels: bug
