### ISSUE TITLE
Permission denied loading ticker.yaml

### ISSUE THREAD

**Issue by bigfoot90** [achannarasappa/ticker#159] opened 2021-04-05 01:48 UTC
**Describe the bug**
I'm using snap package, I've created the configuration file manually and running by `ticker --config $HOME/ticker.yaml` as explained by README.md.
But I'm ending with error `Invalid config: open .ticker.yaml: permission denied`

**To Reproduce**
1. `sudo snap install ticker`
3. `nano ~/ticker.yaml`
4. `ticker --config $HOME/ticker.yaml`

**Expected behavior**
Expecting program loads correctly

**Environment (please complete the following information):**
 - OS: `Ubuntu 20.04`
 - ticker Version: `4.0.6`

**Comment by tmack8080** [comment] 2021-04-05 18:27
I had the same problem. The issue is the snap installer. I think there is
an open bug report for this. I ended up using the Windows version but you
can try to install it manually.

**Comment by achannarasappa** [comment] 2021-05-31 23:03
I've attempt to replicate the issue with the latest version of ticker and can't seem to do so. I'll close this issue for now but let me know if you're still experiencing the issue and I'll reopen.

![image](https://user-images.githubusercontent.com/1489983/120247759-9ba76100-c242-11eb-90fb-b1c9b4a80cb0.png)
![image](https://user-images.githubusercontent.com/1489983/120247798-c1cd0100-c242-11eb-8966-4687a9912d88.png)
![image](https://user-images.githubusercontent.com/1489983/120247809-ca253c00-c242-11eb-99ae-42b168645fe9.png)

**Closed by achannarasappa** 2021-05-31 23:03 UTC
Labels: bug

**Comment by payneWeave** [comment] 2023-02-21 22:00
I was able to replicate it. I originally created a config in my home directory with a name `.ticker.yaml` and changed the name to remove the preceding dot e.g. `ticker.yaml` and it started working.
