### ISSUE TITLE
ERROR RESTY unexpected response from Yahoo API: A3 session cookie missing from response

### ISSUE THREAD

**Issue by kdkd** [achannarasappa/ticker#266] opened 2024-03-27 14:57 UTC
Starting yesterday, ticker loads fine at first but after a minute or two will start saying:

ERROR RESTY unexpected response from Yahoo API: A3 session cookie missing from response, Attempt 1
ERROR RESTY unexpected response from Yahoo API: A3 session cookie missing from response, Attempt 2

over and over again. Quitting and reopening it makes it work again for a little while, but this appears again soon after.

I'm using 4.5.14 on a Mac via homebrew.

**Comment by JacquardCauseway** [comment] 2024-03-27 16:10
Same issue here. Not sure if this is something on Yahoo's end?

**Comment by achannarasappa** [comment] 2024-03-28 14:46
Thanks for reporting this issue. It looks like it could be specific to the EU or another region since I'm not able to replicate here in the US and the contract test is passing. I'll do some move investigation with a proxy today.

**Comment by JacquardCauseway** [comment] 2024-03-28 14:50
Thanks for taking a look! I've been running it for about 2hrs today so far and haven't encountered the issue (Canada), maybe some weird glitch on Yahoo's end yesterday?

**Comment by achannarasappa** [comment] 2024-03-28 14:54
Thanks for the follow up! It could definitely have been some kind of transient outage but good to hear it is working now.

I'll still do a pass with a proxy before closing this issue but sounds like it was just a temporary issue with Yahoo's API.

**Comment by kdkd** [comment] 2024-03-28 15:15
It does seem fixed for me today too. In case this comes up again, I'm in the US.

**Comment by corford** [comment] 2024-04-16 16:25
FYI: I'm seeing this error today (from a EU IP). If I use a US proxy, the error goes away. This happens even if I use coingecko symbols (which I assumed wouldn't need Yahoo?): e.g. `-w SOLANA.CG`

**Comment by achannarasappa** [comment] 2024-04-17 01:53
Thanks for reporting! I'd suggest waiting a day then trying again. It could be an intermittent issue like mentioned above.

**Comment by jeremytammik** [comment] 2024-05-09 19:11
Same issue here. Running this in Europe.

**Comment by achannarasappa** [comment] 2024-06-02 18:40
I've confirmed ticker is working from London, Amsterdam, and Montreal as of today. I expect this was due to an intermittent issue with Yahoo's API so I'll close this issue for now but if it reappears please re-open if there's a persistent problem.

**Closed by achannarasappa** 2024-06-02 18:40 UTC
Labels: bug

**Comment by adriangalilea** [comment] 2024-07-23 10:30
First time I install `ticker`, running it from Spain:

```
» ticker -w NET,AAPL,TSLA

yahoo session refresh error: unexpected response from Yahoo API: A3 session cookie missing from response after agreeing to EU consent request: 400 Bad Request
```

Is it this issue @achannarasappa ?

Thanks

**Comment by SebDominguez** [comment] 2025-01-29 13:09
Same issue

**Comment by ngocphamm** [comment] 2025-01-31 02:26
This is happening to me almost every single day, from the US. Sometimes there will even be more than 1 lines/errors showing up at the bottom like this, while the top will be pushed, and duplicated.

Like other people said, quiting and running `ticker` again would fix it but the issue comes back after a bit (probably random).

![Image](https://github.com/user-attachments/assets/7433ec69-dc09-40a0-9d21-fcc355afd5ba)

I'm using this with tmux, so I'm not sure the pushing up at the top might be related to tmux or not.
